version: 0.2

env:
  shell: bash
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/ttrek-app-repo
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    on-failure: ABORT
    commands:
      - export APP_NAME=ttrek-app
      - chmod 755 -R build.sh
      - mkdir -p ../ttrek-app/artifacts/
      - cp -R codedeploy-scripts/ ../ttrek-app/artifacts/
      - cp -R . ../ttrek-app/artifacts/ttrek-app
      - apt-get update && apt-get install cmake npm -y
      - ./build-new.sh
      - npm init -y
      - npm install chart.js purecss
      - npm install --save-dev \
          @rollup/plugin-typescript \
          rollup-plugin-import-css \
          @rollup/plugin-node-resolve \
          rollup-plugin-inject-process-env \
          @rollup/plugin-commonjs \
          @rollup/plugin-babel \
          @babel/preset-react \
          tslib \
          typescript

      - export CURRENT_DIR=`pwd`
      - export INSTALL_DIR=$CURRENT_DIR/build/install
      - LD_LIBRARY_PATH=$INSTALL_DIR/lib $INSTALL_DIR/bin/tclsh9.0 $INSTALL_DIR/bin/tconfig-encrypt.tcl -app ttrek_sh -env prod -aws_kms_key alias/ttrek-app-kms-key etc/config.ini > etc/config.enc
      # copy dependencies
      - cp -R build ../ttrek-app/artifacts/ttrek-app/
      # copy node_modules
      - cp -R node_modules ../ttrek-app/artifacts/ttrek-app/
      - cp package.json ../ttrek-app/artifacts/ttrek-app/
      - cp package-lock.json ../ttrek-app/artifacts/ttrek-app/
      # copy the encrypted config file
      - cp -R etc ../ttrek-app/artifacts/ttrek-app/
      # compile template files and copy them to the artifacts directory
      - $INSTALL_DIR/bin/tclsh9.0 $INSTALL_DIR/bin/thtml-compiledir.tcl tcl $CURRENT_DIR $CURRENT_DIR/www
      - cp -R cache ../ttrek-app/artifacts/ttrek-app/
      - cp -R public ../ttrek-app/artifacts/ttrek-app/
#      - cp -R certs ../ttrek-app/artifacts/ttrek-app/
      - ls -la ../ttrek-app/artifacts/ttrek-app/
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo `pwd`
      - ls -la
      - cd ../ttrek-app
      - docker build -t $REPOSITORY_URI:latest -f ../ttrek.sh/Dockerfile .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $APP_NAME $REPOSITORY_URI:$IMAGE_TAG > $CODEBUILD_SRC_DIR/imagedefinitions.json
      - |
        CLUSTER_STATUS=`aws ecs describe-clusters --clusters ttrek-app-Cluster --query "clusters[0].status" --output text`

        if [ "$CLUSTER_STATUS" == "ACTIVE" ]; then
            echo "TTrek Cluster is ACTIVE. Force new deployment"
            aws ecs update-service --cluster ttrek-app-Cluster --service TTrekFargateService --force-new-deployment
        fi

artifacts:
  files: $CODEBUILD_SRC_DIR/imagedefinitions.json
  discard-paths: yes
